import { Poppins } from "next/font/google";
import "./globals.css";
import Layout from "@/components/global/layout";
import { RoleProvider } from "./context/RoleContext";
import { ReduxProvider } from "@/redux/provider";
import { Toaster } from "react-hot-toast";

// const mulish = Mulish({
//   weight: ["400", "700", "900", "300", "200"],
//   style: ["normal", "italic"],
//   subsets: ["latin"],
//   display: "swap",
// });
const poppins = Poppins({
  weight: ["400", "700", "900", "300", "200"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Steel Junction",
  description: "Generated by Steel Junction",
};

export default function RootLayout({ children }) {
  return (
    <RoleProvider>
      <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
          integrity="sha512-...your-integrity..."
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
        <body className={poppins.className}>
          <ReduxProvider>
            <RoleProvider>
              <Layout>
                <Toaster />
                {children}
              </Layout>
              {/* {children} */}
            </RoleProvider>
          </ReduxProvider>
        </body>
      </html>
    </RoleProvider>
  );
}
